# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:59:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Accelerator(BaseModel):
    count: Optional[str] = Field(
        None, description='The number of accelerators of this type.'
    )
    installGpuDrivers: Optional[bool] = Field(
        None,
        description='Deprecated: please use instances[0].install_gpu_drivers instead.',
    )
    type: Optional[str] = Field(
        None,
        description='The accelerator type. For example, "nvidia-tesla-t4". See `gcloud compute accelerator-types list`.',
    )


class ActionCondition(BaseModel):
    exitCodes: Optional[List[int]] = Field(
        None,
        description='Exit codes of a task execution. If there are more than 1 exit codes, when task executes with any of the exit code in the list, the condition is met and the action will be executed.',
    )


class State(Enum):
    AGENT_STATE_UNSPECIFIED = 'AGENT_STATE_UNSPECIFIED'
    AGENT_STARTING = 'AGENT_STARTING'
    AGENT_RUNNING = 'AGENT_RUNNING'
    AGENT_STOPPED = 'AGENT_STOPPED'


class AgentMetadata(BaseModel):
    creationTime: Optional[str] = Field(
        None, description='When the VM agent started. Use agent_startup_time instead.'
    )
    creator: Optional[str] = Field(
        None,
        description='Full name of the entity that created this vm. For MIG, this path is: projects/{project}/regions/{region}/InstanceGroupManagers/{igm} The value is retrieved from the vm metadata key of "created-by".',
    )
    imageVersion: Optional[str] = Field(
        None, description='image version for the VM that this agent is installed on.'
    )
    instance: Optional[str] = Field(
        None, description='GCP instance name (go/instance-name).'
    )
    instanceId: Optional[str] = Field(
        None, description='GCP instance ID (go/instance-id).'
    )
    instancePreemptionNoticeReceived: Optional[bool] = Field(
        None, description='If the GCP instance has received preemption notice.'
    )
    osRelease: Optional[Dict[str, str]] = Field(
        None, description='parsed contents of /etc/os-release'
    )
    version: Optional[str] = Field(
        None, description='agent binary version running on VM'
    )
    zone: Optional[str] = Field(None, description='Agent zone.')


class IntendedState(Enum):
    INTENDED_STATE_UNSPECIFIED = 'INTENDED_STATE_UNSPECIFIED'
    ASSIGNED = 'ASSIGNED'
    CANCELLED = 'CANCELLED'
    DELETED = 'DELETED'


class TaskSource(Enum):
    TASK_SOURCE_UNSPECIFIED = 'TASK_SOURCE_UNSPECIFIED'
    BATCH_INTERNAL = 'BATCH_INTERNAL'
    USER = 'USER'


class AgentTimingInfo(BaseModel):
    agentStartupTime: Optional[str] = Field(None, description='Agent startup time')
    bootTime: Optional[str] = Field(None, description='Boot timestamp of the VM OS')
    scriptStartupTime: Optional[str] = Field(
        None, description='Startup time of the Batch VM script.'
    )


class Barrier(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Barriers are identified by their index in runnable list. Names are not required, but if present should be an identifier.',
    )


class CancelOperationRequest(BaseModel):
    pass


class ComputeResource(BaseModel):
    bootDiskMib: Optional[str] = Field(
        None, description='Extra boot disk size in MiB for each task.'
    )
    cpuMilli: Optional[str] = Field(None, description='The milliCPU count.')
    memoryMib: Optional[str] = Field(None, description='Memory in MiB.')


class Container(BaseModel):
    blockExternalNetwork: Optional[bool] = Field(
        None,
        description='If set to true, external network access to and from container will be blocked, containers that are with block_external_network as true can still communicate with each other, network cannot be specified in the `container.options` field.',
    )
    commands: Optional[List[str]] = Field(
        None,
        description='Overrides the `CMD` specified in the container. If there is an ENTRYPOINT (either in the container image or with the entrypoint field below) then commands are appended as arguments to the ENTRYPOINT.',
    )
    entrypoint: Optional[str] = Field(
        None, description='Overrides the `ENTRYPOINT` specified in the container.'
    )
    imageUri: Optional[str] = Field(
        None, description='The URI to pull the container image from.'
    )
    options: Optional[str] = Field(
        None,
        description='Arbitrary additional options to include in the "docker run" command when running this container, e.g. "--network host".',
    )
    password: Optional[str] = Field(
        None,
        description='Optional password for logging in to a docker registry. If password matches `projects/*/secrets/*/versions/*` then Batch will read the password from the Secret Manager;',
    )
    username: Optional[str] = Field(
        None,
        description='Optional username for logging in to a docker registry. If username matches `projects/*/secrets/*/versions/*` then Batch will read the username from the Secret Manager.',
    )
    volumes: Optional[List[str]] = Field(
        None,
        description="Volumes to mount (bind mount) from the host machine files or directories into the container, formatted to match docker run's --volume option, e.g. /foo:/bar, or /foo:/bar:ro",
    )


class Disk(BaseModel):
    diskInterface: Optional[str] = Field(
        None,
        description='Local SSDs are available through both "SCSI" and "NVMe" interfaces. If not indicated, "NVMe" will be the default one for local ssds. We only support "SCSI" for persistent disks now.',
    )
    image: Optional[str] = Field(
        None,
        description='Name of a public or custom image used as the data source. For example, the following are all valid URLs: * Specify the image by its family name: projects/{project}/global/images/family/{image_family} * Specify the image version: projects/{project}/global/images/{image_version} You can also use Batch customized image in short names. The following image values are supported for a boot disk: * "batch-debian": use Batch Debian images. * "batch-centos": use Batch CentOS images. * "batch-cos": use Batch Container-Optimized images.',
    )
    sizeGb: Optional[str] = Field(
        None,
        description="Disk size in GB. For persistent disk, this field is ignored if `data_source` is `image` or `snapshot`. For local SSD, size_gb should be a multiple of 375GB, otherwise, the final size will be the next greater multiple of 375 GB. For boot disk, Batch will calculate the boot disk size based on source image and task requirements if you do not speicify the size. If both this field and the boot_disk_mib field in task spec's compute_resource are defined, Batch will only honor this field.",
    )
    snapshot: Optional[str] = Field(
        None,
        description='Name of a snapshot used as the data source. Snapshot is not supported as boot disk now.',
    )
    type: Optional[str] = Field(
        None,
        description='Disk type as shown in `gcloud compute disk-types list`. For example, local SSD uses type "local-ssd". Persistent disks and boot disks use "pd-balanced", "pd-extreme", "pd-ssd" or "pd-standard".',
    )


class Empty(BaseModel):
    pass


class GCS(BaseModel):
    remotePath: Optional[str] = Field(
        None,
        description='Remote path, either a bucket name or a subdirectory of a bucket, e.g.: bucket_name, bucket_name/subdirectory/',
    )


class ProvisioningModel(Enum):
    PROVISIONING_MODEL_UNSPECIFIED = 'PROVISIONING_MODEL_UNSPECIFIED'
    STANDARD = 'STANDARD'
    SPOT = 'SPOT'
    PREEMPTIBLE = 'PREEMPTIBLE'


class InstanceStatus(BaseModel):
    bootDisk: Optional[Disk] = Field(None, description='The VM boot disk.')
    machineType: Optional[str] = Field(
        None, description='The Compute Engine machine type.'
    )
    provisioningModel: Optional[ProvisioningModel] = Field(
        None, description='The VM instance provisioning model.'
    )
    taskPack: Optional[str] = Field(
        None,
        description='The max number of tasks can be assigned to this instance type.',
    )


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    QUEUED = 'QUEUED'
    SCHEDULED = 'SCHEDULED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    DELETION_IN_PROGRESS = 'DELETION_IN_PROGRESS'


class KMSEnvMap(BaseModel):
    cipherText: Optional[str] = Field(
        None,
        description='The value of the cipherText response from the `encrypt` method.',
    )
    keyName: Optional[str] = Field(
        None,
        description='The name of the KMS key that will be used to decrypt the cipher text.',
    )


class Action(Enum):
    ACTION_UNSPECIFIED = 'ACTION_UNSPECIFIED'
    RETRY_TASK = 'RETRY_TASK'
    FAIL_TASK = 'FAIL_TASK'


class LifecyclePolicy(BaseModel):
    action: Optional[Action] = Field(
        None,
        description='Action to execute when ActionCondition is true. When RETRY_TASK is specified, we will retry failed tasks if we notice any exit code match and fail tasks if no match is found. Likewise, when FAIL_TASK is specified, we will fail tasks if we notice any exit code match and retry tasks if no match is found.',
    )
    actionCondition: Optional[ActionCondition] = Field(
        None,
        description='Conditions that decide why a task failure is dealt with a specific action.',
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"}',
    )
    locationId: Optional[str] = Field(
        None,
        description='The canonical id for this location. For example: `"us-east1"`.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata. For example the available capacity at the given location.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for the location, which may vary between implementations. For example: `"projects/example-project/locations/us-east1"`',
    )


class LocationPolicy(BaseModel):
    allowedLocations: Optional[List[str]] = Field(
        None,
        description='A list of allowed location names represented by internal URLs. Each location can be a region or a zone. Only one region or multiple zones in one region is supported now. For example, ["regions/us-central1"] allow VMs in any zones in region us-central1. ["zones/us-central1-a", "zones/us-central1-c"] only allow VMs in zones us-central1-a and us-central1-c. All locations end up in different regions would cause errors. For example, ["regions/us-central1", "zones/us-central1-a", "zones/us-central1-b", "zones/us-west1-a"] contains 2 regions "us-central1" and "us-west1". An error is expected in this case.',
    )


class Destination(Enum):
    DESTINATION_UNSPECIFIED = 'DESTINATION_UNSPECIFIED'
    CLOUD_LOGGING = 'CLOUD_LOGGING'
    PATH = 'PATH'


class LogsPolicy(BaseModel):
    destination: Optional[Destination] = Field(
        None, description='Where logs should be saved.'
    )
    logsPath: Optional[str] = Field(
        None,
        description='The path to which logs are saved when the destination = PATH. This can be a local file path on the VM, or under the mount point of a Persistent Disk or Filestore, or a Cloud Storage path.',
    )


class NewJobState(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    QUEUED = 'QUEUED'
    SCHEDULED = 'SCHEDULED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    DELETION_IN_PROGRESS = 'DELETION_IN_PROGRESS'


class NewTaskState(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    ASSIGNED = 'ASSIGNED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'
    UNEXECUTED = 'UNEXECUTED'


class Type(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    JOB_STATE_CHANGED = 'JOB_STATE_CHANGED'
    TASK_STATE_CHANGED = 'TASK_STATE_CHANGED'


class Message(BaseModel):
    newJobState: Optional[NewJobState] = Field(None, description='The new job state.')
    newTaskState: Optional[NewTaskState] = Field(
        None, description='The new task state.'
    )
    type: Optional[Type] = Field(None, description='The message type.')


class NFS(BaseModel):
    remotePath: Optional[str] = Field(
        None, description='Remote source path exported from the NFS, e.g., "/share".'
    )
    server: Optional[str] = Field(None, description='The IP address of the NFS.')


class NetworkInterface(BaseModel):
    network: Optional[str] = Field(
        None,
        description='The URL of an existing network resource. You can specify the network as a full or partial URL. For example, the following are all valid URLs: * https://www.googleapis.com/compute/v1/projects/{project}/global/networks/{network} * projects/{project}/global/networks/{network} * global/networks/{network}',
    )
    noExternalIpAddress: Optional[bool] = Field(
        None,
        description='Default is false (with an external IP address). Required if no external public IP address is attached to the VM. If no external public IP address, additional configuration is required to allow the VM to access Google Services. See https://cloud.google.com/vpc/docs/configure-private-google-access and https://cloud.google.com/nat/docs/gce-example#create-nat for more information.',
    )
    subnetwork: Optional[str] = Field(
        None,
        description='The URL of an existing subnetwork resource in the network. You can specify the subnetwork as a full or partial URL. For example, the following are all valid URLs: * https://www.googleapis.com/compute/v1/projects/{project}/regions/{region}/subnetworks/{subnetwork} * projects/{project}/regions/{region}/subnetworks/{subnetwork} * regions/{region}/subnetworks/{subnetwork}',
    )


class NetworkPolicy(BaseModel):
    networkInterfaces: Optional[List[NetworkInterface]] = Field(
        None, description='Network configurations.'
    )


class OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(
        None, description='Output only. API version used to start the operation.'
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time the operation was created.'
    )
    endTime: Optional[str] = Field(
        None, description='Output only. The time the operation finished running.'
    )
    requestedCancellation: Optional[bool] = Field(
        None,
        description='Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.',
    )
    statusMessage: Optional[str] = Field(
        None, description='Output only. Human-readable status of the operation, if any.'
    )
    target: Optional[str] = Field(
        None,
        description='Output only. Server-defined resource path for the target of the operation.',
    )
    verb: Optional[str] = Field(
        None, description='Output only. Name of the verb executed by the operation.'
    )


class PlacementPolicy(BaseModel):
    collocation: Optional[str] = Field(
        None,
        description='UNSPECIFIED vs. COLLOCATED (default UNSPECIFIED). Use COLLOCATED when you want VMs to be located close to each other for low network latency between the VMs. No placement policy will be generated when collocation is UNSPECIFIED.',
    )
    maxDistance: Optional[str] = Field(
        None,
        description='When specified, causes the job to fail if more than max_distance logical switches are required between VMs. Batch uses the most compact possible placement of VMs even when max_distance is not specified. An explicit max_distance makes that level of compactness a strict requirement. Not yet implemented',
    )


class Script(BaseModel):
    path: Optional[str] = Field(
        None,
        description='Script file path on the host VM. To specify an interpreter, please add a `#!`(also known as [shebang line](https://en.wikipedia.org/wiki/Shebang_(Unix))) as the first line of the file.(For example, to execute the script using bash, `#!/bin/bash` should be the first line of the file. To execute the script using`Python3`, `#!/usr/bin/env python3` should be the first line of the file.) Otherwise, the file will by default be excuted by `/bin/sh`.',
    )
    text: Optional[str] = Field(
        None,
        description='Shell script text. To specify an interpreter, please add a `#!\\n` at the beginning of the text.(For example, to execute the script using bash, `#!/bin/bash\\n` should be added. To execute the script using`Python3`, `#!/usr/bin/env python3\\n` should be added.) Otherwise, the script will by default be excuted by `/bin/sh`.',
    )


class ServiceAccount(BaseModel):
    email: Optional[str] = Field(
        None,
        description='Email address of the service account. If not specified, the default Compute Engine service account for the project will be used. If instance template is being used, the service account has to be specified in the instance template and it has to match the email field here.',
    )
    scopes: Optional[List[str]] = Field(
        None,
        description='List of scopes to be enabled for this service account on the VM, in addition to the cloud-platform API scope that will be added by default.',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TaskState(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    ASSIGNED = 'ASSIGNED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'
    UNEXECUTED = 'UNEXECUTED'


class TaskExecution(BaseModel):
    exitCode: Optional[int] = Field(
        None,
        description='When task is completed as the status of FAILED or SUCCEEDED, exit code is for one task execution result, default is 0 as success.',
    )


class TaskGroupStatus(BaseModel):
    counts: Optional[Dict[str, str]] = Field(
        None,
        description='Count of task in each state in the TaskGroup. The map key is task state name.',
    )
    instances: Optional[List[InstanceStatus]] = Field(
        None, description='Status of instances allocated for the TaskGroup.'
    )


class State2(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    ASSIGNED = 'ASSIGNED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'
    UNEXECUTED = 'UNEXECUTED'


class Volume(BaseModel):
    deviceName: Optional[str] = Field(
        None,
        description='Device name of an attached disk volume, which should align with a device_name specified by job.allocation_policy.instances[0].policy.disks[i].device_name or defined by the given instance template in job.allocation_policy.instances[0].instance_template.',
    )
    gcs: Optional[GCS] = Field(None, description='A Google Cloud Storage (GCS) volume.')
    mountOptions: Optional[List[str]] = Field(
        None,
        description='For Google Cloud Storage (GCS), mount options are the options supported by the gcsfuse tool (https://github.com/GoogleCloudPlatform/gcsfuse). For existing persistent disks, mount options provided by the mount command (https://man7.org/linux/man-pages/man8/mount.8.html) except writing are supported. This is due to restrictions of multi-writer mode (https://cloud.google.com/compute/docs/disks/sharing-disks-between-vms). For other attached disks and Network File System (NFS), mount options are these supported by the mount command (https://man7.org/linux/man-pages/man8/mount.8.html).',
    )
    mountPath: Optional[str] = Field(
        None, description='The mount path for the volume, e.g. /mnt/disks/share.'
    )
    nfs: Optional[NFS] = Field(
        None,
        description='A Network File System (NFS) volume. For example, a Filestore file share.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AttachedDisk(BaseModel):
    deviceName: Optional[str] = Field(
        None,
        description='Device name that the guest operating system will see. It is used by Runnable.volumes field to mount disks. So please specify the device_name if you want Batch to help mount the disk, and it should match the device_name field in volumes.',
    )
    existingDisk: Optional[str] = Field(None, description='Name of an existing PD.')
    newDisk: Optional[Disk] = None


class Environment(BaseModel):
    encryptedVariables: Optional[KMSEnvMap] = Field(
        None,
        description='An encrypted JSON dictionary where the key/value pairs correspond to environment variable names and their values.',
    )
    secretVariables: Optional[Dict[str, str]] = Field(
        None,
        description='A map of environment variable names to Secret Manager secret names. The VM will access the named secrets to set the value of each environment variable.',
    )
    variables: Optional[Dict[str, str]] = Field(
        None, description='A map of environment variable names to values.'
    )


class InstancePolicy(BaseModel):
    accelerators: Optional[List[Accelerator]] = Field(
        None, description='The accelerators attached to each VM instance.'
    )
    bootDisk: Optional[Disk] = Field(
        None,
        description='Boot disk to be created and attached to each VM by this InstancePolicy. Boot disk will be deleted when the VM is deleted. Batch API now only supports booting from image.',
    )
    disks: Optional[List[AttachedDisk]] = Field(
        None,
        description='Non-boot disks to be attached for each VM created by this InstancePolicy. New disks will be deleted when the VM is deleted.',
    )
    machineType: Optional[str] = Field(
        None, description='The Compute Engine machine type.'
    )
    minCpuPlatform: Optional[str] = Field(
        None,
        description='The minimum CPU platform. See https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform. Not yet implemented.',
    )
    provisioningModel: Optional[ProvisioningModel] = Field(
        None, description='The provisioning model.'
    )


class InstancePolicyOrTemplate(BaseModel):
    installGpuDrivers: Optional[bool] = Field(
        None,
        description='Set this field true if users want Batch to help fetch drivers from a third party location and install them for GPUs specified in policy.accelerators or instance_template on their behalf. Default is false.',
    )
    instanceTemplate: Optional[str] = Field(
        None,
        description="Name of an instance template used to create VMs. Named the field as 'instance_template' instead of 'template' to avoid c++ keyword conflict.",
    )
    policy: Optional[InstancePolicy] = Field(None, description='InstancePolicy.')


class JobNotification(BaseModel):
    message: Optional[Message] = Field(
        None,
        description='The attribute requirements of messages to be sent to this Pub/Sub topic. Without this field, no message will be sent.',
    )
    pubsubTopic: Optional[str] = Field(
        None,
        description='The Pub/Sub topic where notifications like the job state changes will be published. This topic exist in the same project as the job and billings will be charged to this project. If not specified, no Pub/Sub messages will be sent. Topic format: `projects/{project}/topics/{topic}`.',
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class Runnable(BaseModel):
    alwaysRun: Optional[bool] = Field(
        None,
        description="By default, after a Runnable fails, no further Runnable are executed. This flag indicates that this Runnable must be run even if the Task has already failed. This is useful for Runnables that copy output files off of the VM or for debugging. The always_run flag does not override the Task's overall max_run_duration. If the max_run_duration has expired then no further Runnables will execute, not even always_run Runnables.",
    )
    background: Optional[bool] = Field(
        None,
        description='This flag allows a Runnable to continue running in the background while the Task executes subsequent Runnables. This is useful to provide services to other Runnables (or to provide debugging support tools like SSH servers).',
    )
    barrier: Optional[Barrier] = Field(None, description='Barrier runnable.')
    container: Optional[Container] = Field(None, description='Container runnable.')
    environment: Optional[Environment] = Field(
        None,
        description='Environment variables for this Runnable (overrides variables set for the whole Task or TaskGroup).',
    )
    ignoreExitStatus: Optional[bool] = Field(
        None,
        description='Normally, a non-zero exit status causes the Task to fail. This flag allows execution of other Runnables to continue instead.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Labels for this Runnable.'
    )
    script: Optional[Script] = Field(None, description='Script runnable.')
    timeout: Optional[str] = Field(None, description='Timeout for this Runnable.')


class StatusEvent(BaseModel):
    description: Optional[str] = Field(None, description='Description of the event.')
    eventTime: Optional[str] = Field(None, description='The time this event occurred.')
    taskExecution: Optional[TaskExecution] = Field(None, description='Task Execution')
    taskState: Optional[TaskState] = Field(None, description='Task State')
    type: Optional[str] = Field(None, description='Type of the event.')


class TaskSpec(BaseModel):
    computeResource: Optional[ComputeResource] = Field(
        None, description='ComputeResource requirements.'
    )
    environment: Optional[Environment] = Field(
        None, description='Environment variables to set before running the Task.'
    )
    environments: Optional[Dict[str, str]] = Field(
        None, description='Deprecated: please use environment(non-plural) instead.'
    )
    lifecyclePolicies: Optional[List[LifecyclePolicy]] = Field(
        None,
        description='Lifecycle management schema when any task in a task group is failed. Currently we only support one lifecycle policy. When the lifecycle policy condition is met, the action in the policy will execute. If task execution result does not meet with the defined lifecycle policy, we consider it as the default policy. Default policy means if the exit code is 0, exit task. If task ends with non-zero exit code, retry the task with max_retry_count.',
    )
    maxRetryCount: Optional[int] = Field(
        None,
        description='Maximum number of retries on failures. The default, 0, which means never retry. The valid value range is [0, 10].',
    )
    maxRunDuration: Optional[str] = Field(
        None,
        description='Maximum duration the task should run. The task will be killed and marked as FAILED if over this limit.',
    )
    runnables: Optional[List[Runnable]] = Field(
        None,
        description='The sequence of scripts or containers to run for this Task. Each Task using this TaskSpec executes its list of runnables in order. The Task succeeds if all of its runnables either exit with a zero status or any that exit with a non-zero status have the ignore_exit_status flag. Background runnables are killed automatically (if they have not already exited) a short time after all foreground runnables have completed. Even though this is likely to result in a non-zero exit status for the background runnable, these automatic kills are not treated as Task failures.',
    )
    volumes: Optional[List[Volume]] = Field(
        None, description='Volumes to mount before running Tasks using this TaskSpec.'
    )


class TaskStatus(BaseModel):
    state: Optional[State2] = Field(None, description='Task state')
    statusEvents: Optional[List[StatusEvent]] = Field(
        None, description='Detailed info about why the state is reached.'
    )


class AgentTask(BaseModel):
    intendedState: Optional[IntendedState] = Field(
        None, description='The intended state of the task.'
    )
    reachedBarrier: Optional[str] = Field(
        None,
        description="The highest barrier reached by all tasks in the task's TaskGroup.",
    )
    spec: Optional[TaskSpec] = Field(None, description='Task Spec.')
    status: Optional[TaskStatus] = Field(None, description='Task status.')
    task: Optional[str] = Field(None, description='Task name.')
    taskSource: Optional[TaskSource] = Field(
        None, description='TaskSource represents the source of the task.'
    )


class AgentTaskInfo(BaseModel):
    runnable: Optional[str] = Field(
        None,
        description='The highest index of a runnable started by the agent for this task. The runnables are indexed from 1. Value 0 is undefined.',
    )
    taskId: Optional[str] = Field(None, description='ID of the Task')
    taskStatus: Optional[TaskStatus] = Field(
        None,
        description='The status of the Task. If we need agent specific fields we should fork the public TaskStatus into an agent specific one. Or add them below.',
    )


class AllocationPolicy(BaseModel):
    instances: Optional[List[InstancePolicyOrTemplate]] = Field(
        None,
        description='Describe instances that can be created by this AllocationPolicy. Only instances[0] is supported now.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Labels applied to all VM instances and other resources created by AllocationPolicy. Labels could be user provided or system generated. You can assign up to 64 labels. [Google Compute Engine label restrictions](https://cloud.google.com/compute/docs/labeling-resources#restrictions) apply. Label names that start with "goog-" or "google-" are reserved.',
    )
    location: Optional[LocationPolicy] = Field(
        None,
        description='Location where compute resources should be allocated for the Job.',
    )
    network: Optional[NetworkPolicy] = Field(None, description='The network policy.')
    placement: Optional[PlacementPolicy] = Field(
        None, description='The placement policy.'
    )
    serviceAccount: Optional[ServiceAccount] = Field(
        None, description='Service account that VMs will run as.'
    )


class JobStatus(BaseModel):
    runDuration: Optional[str] = Field(
        None, description='The duration of time that the Job spent in status RUNNING.'
    )
    state: Optional[State1] = Field(None, description='Job state')
    statusEvents: Optional[List[StatusEvent]] = Field(
        None, description='Job status events'
    )
    taskGroups: Optional[Dict[str, TaskGroupStatus]] = Field(
        None,
        description='Aggregated task status for each TaskGroup in the Job. The map key is TaskGroup ID.',
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class ReportAgentStateResponse(BaseModel):
    defaultReportInterval: Optional[str] = Field(
        None, description='Default report interval override'
    )
    minReportInterval: Optional[str] = Field(
        None, description='Minimum report interval override'
    )
    tasks: Optional[List[AgentTask]] = Field(
        None, description='Tasks assigned to the agent'
    )


class Task(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Task name. The name is generated from the parent TaskGroup name and \'id\' field. For example: "projects/123456/locations/us-west1/jobs/job01/taskGroups/group01/tasks/task01".',
    )
    status: Optional[TaskStatus] = Field(None, description='Task Status.')


class TaskGroup(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. TaskGroup name. The system generates this field based on parent Job name. For example: "projects/123456/locations/us-west1/jobs/job01/taskGroups/group01".',
    )
    parallelism: Optional[str] = Field(
        None,
        description='Max number of tasks that can run in parallel. Default to min(task_count, 1000). Field parallelism must be 1 if the scheduling_policy is IN_ORDER.',
    )
    permissiveSsh: Optional[bool] = Field(
        None,
        description='When true, Batch will configure SSH to allow passwordless login between VMs running the Batch tasks in the same TaskGroup.',
    )
    requireHostsFile: Optional[bool] = Field(
        None,
        description='When true, Batch will populate a file with a list of all VMs assigned to the TaskGroup and set the BATCH_HOSTS_FILE environment variable to the path of that file. Defaults to false.',
    )
    taskCount: Optional[str] = Field(
        None, description='Number of Tasks in the TaskGroup. Default is 1.'
    )
    taskCountPerNode: Optional[str] = Field(
        None,
        description='Max number of tasks that can be run on a VM at the same time. If not specified, the system will decide a value based on available compute resources on a VM and task requirements.',
    )
    taskEnvironments: Optional[List[Environment]] = Field(
        None,
        description="An array of environment variable mappings, which are passed to Tasks with matching indices. If task_environments is used then task_count should not be specified in the request (and will be ignored). Task count will be the length of task_environments. Tasks get a BATCH_TASK_INDEX and BATCH_TASK_COUNT environment variable, in addition to any environment variables set in task_environments, specifying the number of Tasks in the Task's parent TaskGroup, and the specific Task's index in the TaskGroup (0 through BATCH_TASK_COUNT - 1). task_environments supports up to 200 entries.",
    )
    taskSpec: Optional[TaskSpec] = Field(
        None, description='Required. Tasks in the group share the same task spec.'
    )


class AgentInfo(BaseModel):
    jobId: Optional[str] = Field(None, description='The assigned Job ID')
    reportTime: Optional[str] = Field(
        None, description='When the AgentInfo is generated.'
    )
    state: Optional[State] = Field(None, description='Agent state.')
    taskGroupId: Optional[str] = Field(None, description='The assigned task group ID.')
    tasks: Optional[List[AgentTaskInfo]] = Field(None, description='Task Info.')


class Job(BaseModel):
    allocationPolicy: Optional[AllocationPolicy] = Field(
        None, description='Compute resource allocation for all TaskGroups in the Job.'
    )
    createTime: Optional[str] = Field(
        None, description='Output only. When the Job was created.'
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Labels for the Job. Labels could be user provided or system generated. For example, "labels": { "department": "finance", "environment": "test" } You can assign up to 64 labels. [Google Compute Engine label restrictions](https://cloud.google.com/compute/docs/labeling-resources#restrictions) apply. Label names that start with "goog-" or "google-" are reserved.',
    )
    logsPolicy: Optional[LogsPolicy] = Field(
        None, description='Log preservation policy for the Job.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Job name. For example: "projects/123456/locations/us-central1/jobs/job01".',
    )
    notifications: Optional[List[JobNotification]] = Field(
        None, description='Notification configurations.'
    )
    priority: Optional[str] = Field(
        None,
        description='Priority of the Job. The valid value range is [0, 100). Default value is 0. Higher value indicates higher priority. A job with higher priority value is more likely to run earlier if all other requirements are satisfied.',
    )
    status: Optional[JobStatus] = Field(
        None, description='Output only. Job status. It is read only for users.'
    )
    taskGroups: Optional[List[TaskGroup]] = Field(
        None,
        description='Required. TaskGroups in the Job. Only one TaskGroup is supported now.',
    )
    uid: Optional[str] = Field(
        None,
        description='Output only. A system generated unique ID (in UUID4 format) for the Job.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The last time the Job was updated.'
    )


class ListJobsResponse(BaseModel):
    jobs: Optional[List[Job]] = Field(None, description='Jobs.')
    nextPageToken: Optional[str] = Field(None, description='Next page token.')
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ListTasksResponse(BaseModel):
    nextPageToken: Optional[str] = Field(None, description='Next page token.')
    tasks: Optional[List[Task]] = Field(None, description='Tasks.')
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ReportAgentStateRequest(BaseModel):
    agentInfo: Optional[AgentInfo] = Field(None, description='Agent info.')
    agentTimingInfo: Optional[AgentTimingInfo] = Field(
        None, description='Agent timing info.'
    )
    metadata: Optional[AgentMetadata] = Field(None, description='Agent metadata.')
